### ISSUE TITLE
Error msg on second dycrypt attempt

### ISSUE THREAD

**Issue by theboy181** [FoxMcloud5655/NEW-NUSGrabberGUI#10]
unable to copy saved common key. Ensure you have access to read and write to the directory that you specified

I was able to decrypt this MK8 DLC once, and then moved the created files. Next decrypt it gave me that error. 

I tested smash DLC and it worked fine.

Thoughts?

**Comment by FoxMcloud5655** [comment]
This error stems from NEW-NUSGrabberGUI remembering where your common key was stored, then not finding it there or not being able to copy it to the directory of the DLC for CDecrypt to use.  Try making sure the directory you specified that your DLC was downloaded to has correct permissions.  Also, make sure that the common key is still where you used it the first time.

**Comment by theboy181** [comment]
Permissions look OK, and I haven't changed anything with the common key location. As I mentioned Im able to dycrypt other directories.

IS there a reset or something I can test ?

UPDATE:

I had to manually delete ckey.bin from the directory in order for it to work. I double checked the file for permissions and they were fine.

Maybe there is a way to have NUSGrabber delete the file first?

**Comment by FoxMcloud5655** [comment]
Glad you got it to work.  I THOUGHT that I had fixed that a long time ago, but apparently not.  Thank you for finding this bug.

Yes, in reference to your last question, it is supposed to automatically work if the ckey.bin is already there.  It defers to NOT deleting the file in case if it is your only copy of the common key.

**Comment by theboy181** [comment]
Well usually you don't get thank for finding a bug. ;). its a pretty sweet tool. Do you do feature requests?

**Comment by FoxMcloud5655** [comment]
In my case, I don't update unless it has something to add, which in this case, it's a bug fix.  The more bugs worked out, the less issues people will have :)  Yes, but do that in a seperate issue.  If it's something I think can be added, I'll add it to a milestone (i.e., coming in 0.92).  If I don't like it, I'll close it.  Simple!
