### ISSUE TITLE
wii u 

### ISSUE THREAD

**Issue by bossaleini** [FoxMcloud5655/NEW-NUSGrabberGUI#11]
New NUSgrabber is not working for my windows 7 i need help i open it and tells me i cant download it
tells me this c:\New NUSgrabber\MSVCR120.dll is either not designed to run on windows or it contains a error. try installing the program again using the original installation media or contact your system administrator or the software vendor for support

so what am i doing worng??? for it not to work on my windows for me and thanks for helping me  :)

**Comment by FoxMcloud5655** [comment]
Have you tried installing the correct version of Visual Studio C++ Runtime (x86)?  If so, delete all of the .DLL files that start with "M" inside of the program's directory and try running it again.

**Comment by bossaleini** [comment]
OK ??

**Comment by bossaleini** [comment]
yes

**Comment by FoxMcloud5655** [comment]
Still not working?  Attach a screenshot of the folder structure.

**Comment by FoxMcloud5655** [comment]
Closed due to nonresponse.
