### ISSUE TITLE
Crashing after Parsing

### ISSUE THREAD

**Issue by demTICKSdoe** [FoxMcloud5655/NEW-NUSGrabberGUI#12]
2/28/2017 10:53:34 PM - Couldn't find CDecrypt.exe.  Extracting resource.
2/28/2017 10:53:34 PM - Couldn't find msvcr120.dll.  Extracting resource.
2/28/2017 10:53:34 PM - Couldn't find msvcp140.dll.  Extracting resource.
2/28/2017 10:53:34 PM - Couldn't find libeay32.dll.  Extracting resource.
2/28/2017 10:53:34 PM - Couldn't find NUSgrabber.exe.  Extracting resource.
2/28/2017 10:53:34 PM - Couldn't find vcruntime140.dll.  Extracting resource.
2/28/2017 10:53:34 PM - Couldn't find wget.exe.  Extracting resource.

NEW-NUSGrabberGUI v0.89 beta started in emulated debug mode on 2/28/2017 10:53:34 PM

2/28/2017 10:53:34 PM - Completed load successfully.
2/28/2017 10:53:34 PM - Connecting to http://wiiubrew.org/wiki/Title_database.
2/28/2017 10:53:58 PM - Parsing data gathered from http://wiiubrew.org/wiki/Title_database.
2/28/2017 10:54:01 PM - Cleaning up unneeded resource: D:\WiiU\nusgrabber\CDecrypt.exe.
2/28/2017 10:54:01 PM - Cleaning up unneeded resource: D:\WiiU\nusgrabber\msvcr120.dll.
2/28/2017 10:54:01 PM - Cleaning up unneeded resource: D:\WiiU\nusgrabber\msvcp140.dll.
2/28/2017 10:54:01 PM - Cleaning up unneeded resource: D:\WiiU\nusgrabber\libeay32.dll.
2/28/2017 10:54:01 PM - Cleaning up unneeded resource: D:\WiiU\nusgrabber\NUSgrabber.exe.
2/28/2017 10:54:01 PM - Cleaning up unneeded resource: D:\WiiU\nusgrabber\vcruntime140.dll.
2/28/2017 10:54:01 PM - Cleaning up unneeded resource: D:\WiiU\nusgrabber\wget.exe.
2/28/2017 10:54:01 PM - Preforming shut down process.

**Comment by Ldrambal1** [comment]
Having this same exact error :(

**Comment by FoxMcloud5655** [comment]
Duplicate thread.  Please post in Issue #7.
