### ISSUE TITLE
NUSGrabber Stopped Working

### ISSUE THREAD

**Issue by reploid** [FoxMcloud5655/NEW-NUSGrabberGUI#13]
1/3/17 8:03:54 PM - Couldn't find CDecrypt.exe.  Extracting resource.
1/3/17 8:03:54 PM - Couldn't find msvcr120.dll.  Extracting resource.
1/3/17 8:03:54 PM - Couldn't find msvcp140.dll.  Extracting resource.
1/3/17 8:03:54 PM - Couldn't find libeay32.dll.  Extracting resource.
1/3/17 8:03:54 PM - Couldn't find NUSgrabber.exe.  Extracting resource.
1/3/17 8:03:54 PM - Couldn't find vcruntime140.dll.  Extracting resource.
1/3/17 8:03:54 PM - Couldn't find wget.exe.  Extracting resource.

NEW-NUSGrabberGUI v0.89 beta started in emulated debug mode on 1/3/17 8:03:54 PM

1/3/17 8:03:54 PM - Completed load successfully.
1/3/17 8:03:54 PM - Connecting to http://wiiubrew.org/wiki/Title_database.
1/3/17 8:03:56 PM - Parsing data gathered from http://wiiubrew.org/wiki/Title_database.
1/3/17 8:04:01 PM - Cleaning up unneeded resource: C:\util\CDecrypt.exe.
1/3/17 8:04:01 PM - Cleaning up unneeded resource: C:\util\msvcr120.dll.
1/3/17 8:04:01 PM - Cleaning up unneeded resource: C:\util\msvcp140.dll.
1/3/17 8:04:01 PM - Cleaning up unneeded resource: C:\util\libeay32.dll.
1/3/17 8:04:01 PM - Cleaning up unneeded resource: C:\util\NUSgrabber.exe.
1/3/17 8:04:01 PM - Cleaning up unneeded resource: C:\util\vcruntime140.dll.
1/3/17 8:04:01 PM - Cleaning up unneeded resource: C:\util\wget.exe.
1/3/17 8:04:01 PM - Preforming shut down process.

**Comment by FoxMcloud5655** [comment]
Duplicate thread.  Please post in Issue #7.
