### ISSUE TITLE
possible issue?

### ISSUE THREAD

**Issue by soapycord** [FoxMcloud5655/NEW-NUSGrabberGUI#15]
The second i open the program my computer immediately says there is an issue and that the program has stopped working. I have Microsoft's .NET Framework 4.5 so i am unsure of what the issue could be.

**Comment by FoxMcloud5655** [comment]
Going back through missed issues; are you still having this problem, or did you find out what the error was?

**Comment by FoxMcloud5655** [comment]
Closing due to no further communications.  If you have this issue still, please comment and I'll reopen the issue!
