### ISSUE TITLE
Issue Downloading Breath of the Wild at 000000b7.h3

### ISSUE THREAD

**Issue by AJMansfield** [FoxMcloud5655/NEW-NUSGrabberGUI#16]
I was attempting to download the 1.1.1 update for Breath of the Wild, but whenever I try to download the update from the program freezes with 'Downloading: 000000b7.h3...' in the search bar and its network usage drops to 0 in task manager.. This occurs regardless of whether 'use old downloader' is checked in the settings.

All the steps I performed leading to the first time I encountered the issue:
 - Windows 10
 - Select 'EUR' region
 - Select 'EUR - The Legend of Zelda Breath of the Wild'
 - Click 'Download'
 - Wait for a few minutes until it reaches 000000b7.h3

Attempting to close the application leaves the NUSgrabber.exe and NUSGrabberGUI processes alive, and they must be manually killed in order to try again.

**Comment by darthsitthiander** [comment]
Same here.

**Comment by FoxMcloud5655** [comment]
This looks to be a NUSGrabber issue.  My program is only a GUI for it.
