### ISSUE TITLE
Add appropriate credit

### ISSUE THREAD

**Issue by curtisy1** [FoxMcloud5655/NEW-NUSGrabberGUI#17]
Looking at the files and codebase, it looks pretty similar to some parts of "NUS Downloader" for Wii (https://github.com/WB3000/nusdownloader). If you used parts of the code of the original project, could you please give credit to the original creator?

I understand you reworked half of the code, but it's still based on WB3000's work in some places, so mentioning him/his project would be fair, I think.

P.S.: I saw that vWii system title downloading and decrypting isn't working. Maybe I'll make a new Pull request for that if you're ok with it.

**Comment by FoxMcloud5655** [comment]
That code is completely unused at the moment, and any parts that are don't work.  If I manage to get it into a usable condition, I will absolutely give credit.  I just didn't want to credit something that was not in use.
