### ISSUE TITLE
NUS Grabber Freezing on specific file

### ISSUE THREAD

**Issue by Vaporeohn** [FoxMcloud5655/NEW-NUSGrabberGUI#20]
![image](https://user-images.githubusercontent.com/33184495/32137631-a9f7b684-bbf1-11e7-8dfe-fb972349add2.png)

it'll stay on this for hours. i have no idea what im doing wrong, is this specific file just that large that it's going to take a while? but then why would it say 100%?

**Comment by FoxMcloud5655** [comment]
This looks to be a NUSGrabber issue.  My program is only a GUI for it.
