### ISSUE TITLE
Can't find the installation directory

### ISSUE THREAD

**Issue by xDqrk** [FoxMcloud5655/NEW-NUSGrabberGUI#22]
Hey, i've just started to try and install free games on my wii u today, but the copy of splatoon that i installed using nusgrabbergui, i can't find it's directory, please reply to this asap

**Comment by FoxMcloud5655** [comment]
Notice those first words you said; "install free games", along with "splatoon", which I KNOW is not a free game for the Wii U.  I will not, and never will, support people trying to pirate games they never paid for.

**Comment by xDqrk** [comment]
fuck u then -.-
