### ISSUE TITLE
There was an unknown problem while downloading

### ISSUE THREAD

**Issue by ghost** [FoxMcloud5655/NEW-NUSGrabberGUI#23]
every time when i try to download any games its says "There was an unknown problem while downloading"

can you please help?

**Comment by ghost** [comment]
False Alarm.
turns out firewall was blocking all the .exe files like wget, NUSgrabber, CDecrypt. 
once i disabled the firewall everything started to download. 

you can close this issue now.

**Comment by FoxMcloud5655** [comment]
Good to know it was resolved!
