### ISSUE TITLE
can't find ckey.bin

### ISSUE THREAD

**Issue by ghost** [FoxMcloud5655/NEW-NUSGrabberGUI#24]
when i try to decrypt the download files it asks me for ckey.bin , where is that file? is it suppose to be in the setup file?

**Comment by FoxMcloud5655** [comment]
This is not the place to ask questions, it's a place to report bugs!  Nonetheless, I'll give you an answer.

ckey.bin is a binary file that contains the Wii U Common Key in hex form.  Legally, I cannot tell you where to find it on the internet, but I can tell you to extract it from your own Wii U System.  Once you have obtained the key, open up a new file in a hex editor (such as HxD) called ckey.bin and paste the key inside.
