### ISSUE TITLE
App does nothing on start. Debug mode fails to start

### ISSUE THREAD

**Issue by tebruno99** [FoxMcloud5655/NEW-NUSGrabberGUI#27]
The app is currently not working. When it starts up the status box says fetching titles and the wiiu_something.txt file shows up and is correct. However the GUI stays disabled except for the Load Titles button.  Clicking on the Load Titles button results in nothing happening.

I tried debug mode, but all it does is decompress wget, and a few exe files and then exits.

**Comment by tebruno99** [comment]
It seems that HtmlAgilityPack is having a hard time parsing the content at wiiubrew.org.  it is unable to find any table elements (even though they exist) in the mw-content  area.

This is as far as I could get atm debugging.

**Comment by OfficialMT22** [comment]
having same issue cant load any titles

**Comment by FoxMcloud5655** [comment]
Fixed in latest commit.
