### ISSUE TITLE
MSVCP120.dll was not found

### ISSUE THREAD

**Issue by stzokev** [FoxMcloud5655/NEW-NUSGrabberGUI#30]
I already have the latest Visual C++ redistro installed (both x86 and x64) from MS official site here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads specifically the ones under Visual Studio 2015, 2017 and 2019 which are version 14.24.28127.4.

NEW-NUSGrabberGUI is version 0.92 (latest). When I select a title and click download I get: "The code execution cannot proceed because MSVCP120.dll was not found. Reinstalling the program may fix this problem."

OS is Windows 10 Pro, ver 1909, build 18363.592.

Thank you!

**Comment by matchman72** [comment]
You may install Visual Studio 2013 (VC++ 12.0) x86 to fix the MSVCP120.dll missing issue

**Comment by stzokev** [comment]
@FoxMcloud5655 That did not fix it, installed version is 12.0.40664. Did you test on your side?

**Comment by FoxMcloud5655** [comment]
Are you sure it was the x86 version, and not the x64 version?  The two are not interchangable.

**Comment by stzokev** [comment]
It was the x86, but did not take until I just rebooted the machine. Now it works! Last question - where is the download folder for the tool?
