### ISSUE TITLE
Unknown Issue?

### ISSUE THREAD

**Issue by Musicbro27** [FoxMcloud5655/NEW-NUSGrabberGUI#8]
I get an error while trying to download and it says "There was an unknown issue while downloading" Please help me. I was downloading Super Mario Maker USA Latest.

**Comment by ghost** [comment]
i have the same problem you downloaded it for the cemu?

**Comment by Musicbro27** [comment]
I have.

**Comment by FoxMcloud5655** [comment]
Let's see a "debug.log".  That should explain the error.  To put the program in debug mode, rename NEW-NUSGrabberGUI.exe to NUSGrabberGUI.exe.  Basically, remove the "NEW-".
